backend:
  name: github
  repo: njdancer/njdancer.github.io
  branch: nextjs # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
site_url: http://localhost:3000
# site_url: https://nick.dncr.me
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: posts
    create: true
    delete: true
    extension: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Publish Date", name: "date", widget: datetime }
      - { label: "Body", name: "body", widget: markdown }
      - { label: "Tags", name: "tags", widget: list }
